###注册 中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 80
###网关名称
spring:
  application:
    name: service-zuul
  cloud:
    config:
      ####读取后缀
      profile: dev
      ####读取config-server注册地址
      discovery:
        service-id: config-server
        enabled: true

###默认服务读取eureka注册服务列表 默认间隔30秒

###开启所有监控中心接口
management:
  endpoints:
    web:
      exposure:
        include: "*"

#### 配置网关反向代理
#zuul:
#  routes:
#    api-aapi-b:
#      ### 以 /api-a/访问转发A服务
#      path: /api-a/**
#      serviceId: app-service-a
#    api-b:
#      ### 以 /api-b/
#      path: /api-b/**
#      serviceId: app-service-b

##Zuul整合Ribbon
#api-a:
#  ribbon:
#    listOfServers: http://localhost:8081,http://localhost:8082
#ribbon:
#  eureka:
#    enabled: false